# AI Summit London Hackathon Challenge
* Challenge 1: Using this data, compute what fraction of total EU GHG emissions are attributable to agriculture as a whole
* Challenge 2: Using this data, compute the fraction of total EU GHG emissions attributable to each agricultural product
* Challenge 3: Design an ideal diet that meets nutrition requirements while minimizing environmental cost

**Team : Swansea University**
* Bruce Williams
* Aydan Howell

# Challenge 1:
 Using this data, compute what fraction of total EU GHG emissions are attributable to agriculture as a whole

$
C1 =\frac{Eu\_Agric\_Emissions}{Eu\_Total\_Emissions}
$
<br>
$Eu\_Agric\_Emissions = 310(mt)$
<br>
$Eu\_Total\_Emissions= 4483(mt)$
<br>
$C1 =\frac{469}{4483}=6.936\%$

# Challenge 2:
Using this data, compute the fraction of total EU GHG emissions attributable to each agricultural product

$
Px =\frac{Eu\_Agric\_Food\_Product\_Emissions}{Eu\_Total\_Emissions}
$
<br>
<br>
Cereals excl. rice - $P1 = 1.125\%$
<br>
Hen eggs, in shell - $P2 = 0.107\%$
<br>
Buffalo meat - $P3 = 0.007\%$
<br>
Cattle meat - $P4 = 2.390\%$
<br>
Chicken meat - $P5 = 0.066\%$
<br>
Goat meat - $P6 = 0.035\%$
<br>
Pig meat - $P7 = 0.787\%$
<br>
Sheep meat - $P8 = 0.249\%$
<br>
Buffalo milk - $P9 = 0.011\%$
<br>
Cow milk - $P10 = 1.752\%$
<br>
Goat milk - $P11 = 0.043\%$
<br>
Sheep milk - $P12 = 0.160\%$
<br>
Rice, paddy - $P13 = 0.205\%$
<br>

# Challenge 3 - incomplete :( 

Design an ideal diet that meets nutrition requirements while minimizing environmental cost

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

# Data preprocessing

In [3]:
# Abridged from supplied dataset to remove nutrients with mismatching units
daily_nutrients_reqs = {
    "calcium" : 1300,
    "cholestrol" : 2300,
    "choline": 300,
    "copper" : 35,
    "iron" : 150,
    "lipids" : 28,
    "magnesium" : 18,
    "manganese" : 420,
    "panto_acid" : 16,
    "phosphorous" : 5,
    "potassium" : 1250,
    "protein" : 4700,
    "thiamin" : 2300,
    "vit b12" : 900,
    "vit c" : 2,
    "vit d" : 90
    }

In [4]:
nutrient_data = pd.read_excel('./drive/MyDrive/AIHack/RequiredProducts.xlsx')

In [5]:
display(nutrient_data)

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,GmWt_Desc1,GmWt_2,GmWt_Desc2,Refuse_Pct,0,0.1,0.2,0.3,0.4,0.5
0,3996,"Babyfood, Multigrain whole grain cereal, dry f...",4.58,407,6.67,6.67,2.03,80.06,6.7,26.67,...,0,0.0,0,0,1,0,0,0,1,Cereals
1,8001,"CEREALS RTE,KELLOGG,KELLOGG'S ALL-BRAN ORIGINAL",2.12,259,13.14,4.90,5.60,74.24,29.3,15.69,...,".5 cup, (1 NLEA serving)",0.0,0,0,1,0,0,0,2,Egg
2,8002,"CEREALS RTE,POST,ALPHA-BITS",1.20,389,10.00,4.60,3.90,80.30,7.1,21.00,...,"1 cup, (1 NLEA serving for adults)",20.0,".67 cup, (1 serving for children under 4 years)",0,1,0,0,0,3,Buffalo meat
3,8003,"CEREALS RTE,KELLOGG,KELLOGG'S APPL JACKS",2.50,375,5.10,3.40,1.40,88.20,9.3,43.70,...,"1 cup, (1 NLEA serving)",0.0,0,0,1,0,0,0,4,Cattle meat
4,8005,"CEREALS RTE,KELLOGG,KELLOGG'S ALL-BRAN BRAN BUDS",3.00,257,8.90,2.50,4.48,81.00,42.5,26.70,...,".333 cup, (1 NLEA serving)",0.0,0,0,1,0,0,0,5,Chicken meat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2159,20058,"RICE,WHITE,STMD,CHINESE RESTAURANT",62.50,151,3.20,0.27,0.14,33.88,0.9,0.00,...,"1 cup, loosely packed",0.0,0,0,13,0,0,0,0,0
2160,1108,"MILK,INDIAN BUFFALO,FLUID",83.39,97,3.75,6.89,0.79,5.18,0.0,0.00,...,1 cup,976.0,1 quart,0,9,0,0,0,0,0
2161,1077,"MILK,WHL,3.25% MILKFAT,W/ ADDED VITAMIN D",88.13,61,3.15,3.25,0.67,4.80,0.0,5.05,...,1 cup,30.5,1 fl oz,0,10,0,0,0,0,0
2162,1211,"MILK,WHL,3.25% MILKFAT,WO/ ADDED VIT A & VITAM...",88.13,61,3.15,3.27,0.67,4.78,0.0,5.05,...,1 cup,15.0,1 tbsp,0,10,0,0,0,0,0
2163,1109,"MILK,SHEEP,FLUID",80.70,108,5.98,7.00,0.96,5.36,0.0,0.00,...,1 cup,980.0,1 quart,0,12,0,0,0,0,0

Method 1- Random Search

We use random search to get a benchmark value 
Variables:
diet_size (between 4 & 40)

In [6]:
np.random.seed(13)

In [7]:
def getNutrientValue(item, nutrient):
  return nutrient_data[nutrient][item]

In [8]:
def score(diet):
  # First calculate nutrition %
  nutrients = ["calcium","cholestrol","choline","copper","iron","lipids","magnesium","manganese","panto_acid","phosphorous","potassium","protein","thiamin","vit b12","vit c","vit d"]
  nutrient_req_values = [1300,2300,300,35,150,28,18,420,16,5,1250,4700,2300,900,2,90]
  diet_nut = np.empty(len(diet),len(nutrients))
  diet_nut_percentage = np.empty(len(diet))

#For each item, calculate the percentage of nutrient requirement fulfilled
  for i in range(len(diet_nut)):
    for j in range(0,len(nutrients)):
      diet_nut[item][i] += getNutrientValue(item[0], i) / nutrient_req_values[i]
    diet_nut_percentage[i] = np.mean(diet_nut, axis=1)

  return np.mean(diet_nut_percentage)

Initialise Diet

In [9]:
diet_size = np.random.randint(4,40)

In [10]:
diet_items = np.random.randint(0,2165,diet_size)
print(diet_items)

[  74  866 1780  153  748  922 1268 1986 1462 1865  843 1427 1013   75
    1 1304   11  844 1338 1558  487  389]

In [11]:
diet = dict.fromkeys(diet_items, 0)
diet_mass = 0
for item in diet:
  item_mass = np.random.randint(50,500)
  if (diet_mass + item_mass >2000):
    item_mass = 0
  else:
    diet(item) = item_mass
    diet_mass += item_mass

SyntaxError: ignored